---
title: "Instruções - Projeto 1⚙️"
format: 
    html:
        css: estilo.css
---

## Prazo de entrega

- Prazo final de entrega do relatório técnico: às **23:59 do dia 20/10/2026**.

- **Não será aceito** relatório técnico fora do prazo ou entregue por e-mail.

## Trabalho

Para realizar este projeto, a equipe deve utilizar os dados brutos disponível em *dados de fluido de corte* no moodle. Este arquivo reúne diferentes formulações (sintéticos, semi-sintéticos, vegetais), composições de aditivos e os resultados dos ensaios.

Nesse contexto, o que a equipe deve fazer:

- **Preparação dos dados**: limpar a base de dados e organizar as variáveis.

- **Estabelecimento de critérios**: definir e justificar as variáveis que serão utilizadas na análise.

- **Aplicação do método estatístico**: escolher a metodologia estatística dentre as que foram vistas no curso.

- **Ranqueamento**: com base no método escolhido, classificar os fluidos do melhor para o pior.

- **Relatório técnico**: apresentar o desenvolvimento do projeto em um relatório cujo o template esta disponível no moodle em *Template - relatório técnico*. 

<br>
**Observações**: 

A equipe tem total liberdade para escolher o recurso computacional para auxiliar nas análises.

## Avaliação

A nota do relatório técnico faz parte da nota da apresentação que corresponde a **quatro pontos**.

A avaliação será de acordo com os seguintes itens:

- **Relatório técnico - 2,0 pontos**

(0,25) **Estrutura do trabalho (template)**: o trabalho deve obedecer rigorosamente à estrutura e formatação do template fornecido.

(0,50) **Apresentação geral e escrita científica**: texto bem escrito, coeso, com linguagem científica e objetiva. Figuras e tabelas devidamente ajustadas e referenciadas no texto.

(1,00) **Método estatístico**: descrição e aplicação correta do método estatístico escolhido, incluindo as ferramentas computacionais utilizadas. 

(0,25) **Conclusão**: apresentar quais os melhores e piores fluidos de corte.

- **Apresentação em grupo - 2,0 pontos**

(0,50) **Domínio do conteúdo**: demonstração de conhecimento sobre o problema estudado, metodologia empregada, método estatístico, resultados e conclusões.

(0,20) **Clareza e organização da apresentação**: apresentação estruturada de forma lógica e utilização adequada dos recursos visuais.

(0,70) **Participação e integração da equipe**: distribuição equilibrada das falas entre os integrantes, articulação entre as diferentes partes da apresentação e demonstração de conhecimento do trabalho pela equipe.

(0,40) **Arguição**: capacidade de responder aos questionamentos, demonstrando domínio do trabalho e capacidade de justificar as escolhas metodológicas e os resultados obtidos.

(0,20) **Tempo de apresentação**: cumprimento do tempo máximo estabelecido de 25 minutos.

Entre 20 e 25 min (inclusive): 0,20 ponto;
de 25 a 28 min: 0,10 ponto e;
mais de 28 min e menos do que 20 min: 0,00 ponto.
    
<br>
**Observações**: 

- **Cópias de relatório** serão avaliadas como zero.

- **Relatório mal feito** será avaliado como zero. 

- **Havendo a necessidade**, a nota poderá variar entre os membros da equipe.

## Considerações finais

- Utilizar códigos disponíveis na *internet* ou gerados por inteligência artificial (IA) será permitido. Entretanto, a escrita da análise deve ser de autoria do própria equipe. Citar a referência e/ou fazer uma declaração de uso de ferramenta de IA.

- A equipe deverá entender os códigos utilizados na análise.

- Textos gerados por ferramentas de inteligência artificial (IA) sem a declaração de utilização da ferramenta serão penalizados com desconto de dois pontos na nota final.

